# Generated by Django 2.2.5 on 2019-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Logo1.jpg', upload_to='profile_pics'),
        ),
    ]
