# Generated by Django 2.2.5 on 2019-11-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191107_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Logo.jpg', upload_to='profile_pics'),
        ),
    ]
