# Generated by Django 2.2 on 2019-06-26 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
