# Generated by Django 2.2.5 on 2019-10-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
