# Generated by Django 2.2.5 on 2019-11-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Drafsted', max_length=20),
        ),
    ]
