# Generated by Django 2.1.3 on 2019-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20190214_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='searched_by',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='searched_status',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
