# Generated by Django 2.1.3 on 2019-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20190216_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='searched_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='results',
            name='searched_status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
